// Terra Nova Plus - HD 640x400: the injected code, its data and the game patches exist in two flavours,
// one per executable (HdPayloadFr.cs for the French GOG game, HdPayloadEn.cs for the English GOG / Steam
// game, both generated by _MODS/re/hd_mod.py). This picks the one matching the game that runs.
using System;

static class HdPayload
{
    public static uint Zone, End, PoolBase, Code, Data, Smoothing, HudFilter, Frames, PoolMax, DriverMode, Valid, HdWidth, HdHeight, PoolVar;
    public static byte[] CodeBytes, DataInit;
    public static uint[] PatchAt;
    public static byte[][] PatchOld, PatchNew;
    public static bool English;

    public static void Use(bool english)
    {
        English = english;
        if (english)
        {
            Zone = HdPayloadEn.Zone; End = HdPayloadEn.End; PoolBase = HdPayloadEn.PoolBase; Code = HdPayloadEn.Code; Data = HdPayloadEn.Data;
            Smoothing = HdPayloadEn.Smoothing; HudFilter = HdPayloadEn.HudFilter; Frames = HdPayloadEn.Frames;
            PoolMax = HdPayloadEn.PoolMax; DriverMode = HdPayloadEn.DriverMode; Valid = HdPayloadEn.Valid;
            HdWidth = HdPayloadEn.HdWidth; HdHeight = HdPayloadEn.HdHeight; PoolVar = HdPayloadEn.PoolVar;
            CodeBytes = HdPayloadEn.CodeBytes; DataInit = HdPayloadEn.DataInit;
            PatchAt = HdPayloadEn.PatchAt; PatchOld = HdPayloadEn.PatchOld; PatchNew = HdPayloadEn.PatchNew;
        }
        else
        {
            Zone = HdPayloadFr.Zone; End = HdPayloadFr.End; PoolBase = HdPayloadFr.PoolBase; Code = HdPayloadFr.Code; Data = HdPayloadFr.Data;
            Smoothing = HdPayloadFr.Smoothing; HudFilter = HdPayloadFr.HudFilter; Frames = HdPayloadFr.Frames;
            PoolMax = HdPayloadFr.PoolMax; DriverMode = HdPayloadFr.DriverMode; Valid = HdPayloadFr.Valid;
            HdWidth = HdPayloadFr.HdWidth; HdHeight = HdPayloadFr.HdHeight; PoolVar = HdPayloadFr.PoolVar;
            CodeBytes = HdPayloadFr.CodeBytes; DataInit = HdPayloadFr.DataInit;
            PatchAt = HdPayloadFr.PatchAt; PatchOld = HdPayloadFr.PatchOld; PatchNew = HdPayloadFr.PatchNew;
        }
    }
}
