// Terra Nova Plus - HD 640x400: the injected code, its data and the game patches exist in two flavours,
// one per executable (HdPayloadFr.cs for the French GOG game, HdPayloadEn.cs for the English GOG / Steam
// game, both generated by _MODS/re/hd_mod.py). This picks the one matching the game that runs.
using System;

static class HdPayload
{
    public static uint Zone, End, PoolBase, Code, Data, Smoothing, HudFilter, Frames, PoolMax, DriverMode, Valid, HdWidth, HdHeight, PoolVar, HudStretch, Code2, AntiFlicker;
    public static byte[] CodeBytes, DataInit, Code2Bytes;
    public static uint[] PatchAt;
    public static byte[][] PatchOld, PatchNew;
    public static bool English;

    public static void Use(bool english, bool wide)
    {
        English = english;
        if (wide && english)
        {
            Zone = HdPayloadEnWide.Zone; End = HdPayloadEnWide.End; PoolBase = HdPayloadEnWide.PoolBase; Code = HdPayloadEnWide.Code; Data = HdPayloadEnWide.Data;
            Smoothing = HdPayloadEnWide.Smoothing; HudFilter = HdPayloadEnWide.HudFilter; Frames = HdPayloadEnWide.Frames;
            PoolMax = HdPayloadEnWide.PoolMax; DriverMode = HdPayloadEnWide.DriverMode; Valid = HdPayloadEnWide.Valid;
            HdWidth = HdPayloadEnWide.HdWidth; HdHeight = HdPayloadEnWide.HdHeight; PoolVar = HdPayloadEnWide.PoolVar;
            HudStretch = HdPayloadEnWide.HudStretch; CodeBytes = HdPayloadEnWide.CodeBytes; DataInit = HdPayloadEnWide.DataInit;
            Code2 = HdPayloadEnWide.Code2; AntiFlicker = HdPayloadEnWide.AntiFlicker; Code2Bytes = HdPayloadEnWide.Code2Bytes;
            PatchAt = HdPayloadEnWide.PatchAt; PatchOld = HdPayloadEnWide.PatchOld; PatchNew = HdPayloadEnWide.PatchNew;
        }
        else if (wide)
        {
            Zone = HdPayloadFrWide.Zone; End = HdPayloadFrWide.End; PoolBase = HdPayloadFrWide.PoolBase; Code = HdPayloadFrWide.Code; Data = HdPayloadFrWide.Data;
            Smoothing = HdPayloadFrWide.Smoothing; HudFilter = HdPayloadFrWide.HudFilter; Frames = HdPayloadFrWide.Frames;
            PoolMax = HdPayloadFrWide.PoolMax; DriverMode = HdPayloadFrWide.DriverMode; Valid = HdPayloadFrWide.Valid;
            HdWidth = HdPayloadFrWide.HdWidth; HdHeight = HdPayloadFrWide.HdHeight; PoolVar = HdPayloadFrWide.PoolVar;
            HudStretch = HdPayloadFrWide.HudStretch; CodeBytes = HdPayloadFrWide.CodeBytes; DataInit = HdPayloadFrWide.DataInit;
            Code2 = HdPayloadFrWide.Code2; AntiFlicker = HdPayloadFrWide.AntiFlicker; Code2Bytes = HdPayloadFrWide.Code2Bytes;
            PatchAt = HdPayloadFrWide.PatchAt; PatchOld = HdPayloadFrWide.PatchOld; PatchNew = HdPayloadFrWide.PatchNew;
        }
        else if (english)
        {
            Zone = HdPayloadEn.Zone; End = HdPayloadEn.End; PoolBase = HdPayloadEn.PoolBase; Code = HdPayloadEn.Code; Data = HdPayloadEn.Data;
            Smoothing = HdPayloadEn.Smoothing; HudFilter = HdPayloadEn.HudFilter; Frames = HdPayloadEn.Frames;
            PoolMax = HdPayloadEn.PoolMax; DriverMode = HdPayloadEn.DriverMode; Valid = HdPayloadEn.Valid;
            HdWidth = HdPayloadEn.HdWidth; HdHeight = HdPayloadEn.HdHeight; PoolVar = HdPayloadEn.PoolVar;
            HudStretch = 0; CodeBytes = HdPayloadEn.CodeBytes; DataInit = HdPayloadEn.DataInit;
            Code2 = HdPayloadEn.Code2; AntiFlicker = HdPayloadEn.AntiFlicker; Code2Bytes = HdPayloadEn.Code2Bytes;
            PatchAt = HdPayloadEn.PatchAt; PatchOld = HdPayloadEn.PatchOld; PatchNew = HdPayloadEn.PatchNew;
        }
        else
        {
            Zone = HdPayloadFr.Zone; End = HdPayloadFr.End; PoolBase = HdPayloadFr.PoolBase; Code = HdPayloadFr.Code; Data = HdPayloadFr.Data;
            Smoothing = HdPayloadFr.Smoothing; HudFilter = HdPayloadFr.HudFilter; Frames = HdPayloadFr.Frames;
            PoolMax = HdPayloadFr.PoolMax; DriverMode = HdPayloadFr.DriverMode; Valid = HdPayloadFr.Valid;
            HdWidth = HdPayloadFr.HdWidth; HdHeight = HdPayloadFr.HdHeight; PoolVar = HdPayloadFr.PoolVar;
            HudStretch = 0; CodeBytes = HdPayloadFr.CodeBytes; DataInit = HdPayloadFr.DataInit;
            Code2 = HdPayloadFr.Code2; AntiFlicker = HdPayloadFr.AntiFlicker; Code2Bytes = HdPayloadFr.Code2Bytes;
            PatchAt = HdPayloadFr.PatchAt; PatchOld = HdPayloadFr.PatchOld; PatchNew = HdPayloadFr.PatchNew;
        }
    }
}
