// Terra Nova Plus - game keys (KEYBOARD tab): every command of the game's key card can be given another key or
// combination. The game reads the keyboard in one interrupt handler (its keyboard library: an event queue of
// "scancode | press << 8" words and a key state array); a routine of ours, called from that handler, turns the key
// pressed into the game's own one before the game sees it, and adds or hides Alt / Ctrl / Shift events around it
// (the game follows the modifiers from the queue). Only during missions: menus and names typed stay as they are.
// The handler has run since the game started, so DOSBox's dynamic core keeps it compiled and a patch written from
// outside would not be seen: the call to our routine is written by the game itself, from a hook in the camera
// set-up of the first mission (code not run before). Generated by _MODS/re/kb_cave.py (tested in an emulator).
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

static partial class TNPlus
{
    // one command of the game: default and current key (scancode, 0x80 + code for E0 keys) and modifier
    // (0 none, 1 Shift, 2 Ctrl, 3 Alt)
    class GameKey
    {
        public string Id, Group, Name; public int DefSc, DefMod, Sc, Mod, Mouse; public bool Fixed;
        public bool Changed { get { return Sc != DefSc || Mod != DefMod; } }
    }
    static readonly string[] MOD_NAMES = { "", "SHIFT", "CTRL", "ALT" };
    static readonly string[] KEY_GROUPS = { "MOVEMENT", "VIEW", "WEAPONS", "SQUAD", "MAP", "DRONE", "SYSTEM" };
    static readonly List<GameKey> GameKeys = BuildGameKeys();

    static List<GameKey> BuildGameKeys()
    {
        List<GameKey> l = new List<GameKey>();
        Action<string, string, string, int, int, bool> k = (g, id, name, sc, mod, fix) =>
            l.Add(new GameKey { Group = g, Id = id, Name = name, DefSc = sc, DefMod = mod, Sc = sc, Mod = mod, Fixed = fix });
        // from the game's key card (Quick Reference Card)
        k("MOVEMENT", "fwd", "Forward", 0x11, 0, false); k("MOVEMENT", "back", "Back", 0x2D, 0, false);
        k("MOVEMENT", "turnl", "Turn left", 0x1E, 0, false); k("MOVEMENT", "turnr", "Turn right", 0x20, 0, false);
        k("MOVEMENT", "stop", "Stop", 0x1F, 0, false); k("MOVEMENT", "sidel", "Sidestep left", 0x2C, 0, false);
        k("MOVEMENT", "sider", "Sidestep right", 0x2E, 0, false); k("MOVEMENT", "jump", "Jump jets", 0x39, 0, false);
        k("MOVEMENT", "crouch", "Crouch", 0x29, 0, false);
        k("VIEW", "lookup", "Look up", 0x13, 0, false); k("VIEW", "lookdn", "Look down", 0x2F, 0, false);
        k("VIEW", "lookl", "Look left", 0x10, 0, false); k("VIEW", "lookr", "Look right", 0x12, 0, false);
        k("VIEW", "centre", "Centre view", 0x21, 0, false); k("VIEW", "v360", "360 view", 0x30, 0, false);
        k("VIEW", "full", "Full-screen", 0x22, 0, false); k("VIEW", "ir", "Infrared", 0x17, 0, false);
        k("VIEW", "zoomin", "HUD zoom in", 0x0D, 0, false); k("VIEW", "zoomout", "HUD zoom out", 0x0C, 0, false);
        k("VIEW", "mfd", "MFDs full-screen", 0x0F, 0, false);
        for (int w = 1; w <= 4; w++) k("WEAPONS", "w" + w, "Weapon " + w, 1 + w, 0, false);
        k("WEAPONS", "asf", "Use ASF", 0x06, 0, false); k("WEAPONS", "tnext", "Next target", 0x14, 0, false);
        k("WEAPONS", "tprev", "Previous target", 0x15, 0, false);
        for (int s = 1; s <= 3; s++) k("SQUAD", "sq" + s, "Call squadmate " + s, 0x3A + s, 0, false);
        k("SQUAD", "sqall", "Call entire squad", 0x3E, 0, false); k("SQUAD", "drop", "Call dropship", 0x1C, 0, false);
        k("SQUAD", "o_attack", "Aggressive attack", 0x1E, 3, false); k("SQUAD", "o_cover", "Find cover", 0x2E, 3, false);
        k("SQUAD", "o_caution", "Cautious advance", 0x20, 3, false); k("SQUAD", "o_form", "Assume formation", 0x21, 3, false);
        k("SQUAD", "o_hold", "Hold fire", 0x23, 3, false); k("SQUAD", "o_follow", "Follow me", 0x32, 3, false);
        k("SQUAD", "o_nav", "Go to nav point", 0x31, 3, false); k("SQUAD", "o_pickup", "Go to pickup point", 0x19, 3, false);
        k("SQUAD", "o_retreat", "Retreat", 0x13, 3, false); k("SQUAD", "o_status", "Status check", 0x1F, 3, false);
        k("SQUAD", "o_target", "Attack my target", 0x14, 3, false);
        k("MAP", "recentre", "Recentre map", 0x31, 0, false); k("MAP", "maphud", "Map to HUD", 0x32, 0, false);
        k("MAP", "mapout", "Map zoom out", 0x33, 0, false); k("MAP", "mapin", "Map zoom in", 0x34, 0, false);
        k("MAP", "squadinfo", "Squad info", 0x43, 0, false); k("MAP", "sensor", "Sensor range", 0x44, 0, false);
        k("MAP", "wrange", "Weapon range", 0x57, 0, false); k("MAP", "minfo", "Mission info", 0x58, 0, false);
        k("DRONE", "d_up", "Drone up", 0xC9, 2, false); k("DRONE", "d_down", "Drone down", 0xD1, 2, false);
        k("DRONE", "d_recall", "Recall drone", 0xC7, 2, false);
        k("SYSTEM", "pause", "Pause", 0x19, 0, false); k("SYSTEM", "objectives", "Objectives", 0x42, 0, false);
        k("SYSTEM", "help", "Help", 0x35, 0, false); k("SYSTEM", "exit", "Exit game", 0x2D, 3, false);
        k("SYSTEM", "options", "Options", 0x18, 0, true); k("SYSTEM", "abort", "Abort mission", 0x01, 2, true);
        return l;
    }

    static GameKey FindGameKey(string id) { return GameKeys.Find(g => g.Id == id); }

    // plain key of a command for the tool's own use (noclip moves follow the game's), or its default
    static int PlainKey(string id, int def)
    {
        GameKey g = FindGameKey(id);
        return g != null && g.Mod == 0 && g.Sc < 0x80 ? g.Sc : def;
    }

    static string ScanName(int sc)
    {
        switch (sc)
        {
            case 0xC9: return "PGUP"; case 0xD1: return "PGDN"; case 0xC7: return "HOME"; case 0xCF: return "END";
            case 0xC8: return "UP"; case 0xD0: return "DOWN"; case 0xCB: return "LEFT"; case 0xCD: return "RIGHT";
            case 0xD2: return "INS"; case 0xD3: return "DEL"; case 0x01: return "ESC"; case 0x39: return "SPACE";
            case 0x1C: return "ENTER"; case 0x0F: return "TAB";
        }
        return KeyName(sc);
    }
    static string ChordName(int sc, int mod) { return (mod > 0 ? MOD_NAMES[mod] + "+" : "") + ScanName(sc); }

    // ini: key_game_<id> = [SHIFT+|CTRL+|ALT+]scancode (hex), only the changed ones
    static void ParseGameKey(string id, string v)
    {
        GameKey g = FindGameKey(id);
        if (g == null || g.Fixed) return;
        int mod = 0; string s = v.ToUpperInvariant();
        for (int m = 1; m < 4; m++) if (s.StartsWith(MOD_NAMES[m] + "+")) { mod = m; s = s.Substring(MOD_NAMES[m].Length + 1); }
        int sc = Convert.ToInt32(s, 16);
        if (sc > 0 && sc < 0x80) { g.Sc = sc; g.Mod = mod; }
    }
    static string GameKeysIni()
    {
        StringBuilder sb = new StringBuilder();
        foreach (GameKey g in GameKeys)
            if (g.Changed) sb.Append("key_game_" + g.Id + " = " + (g.Mod > 0 ? MOD_NAMES[g.Mod] + "+" : "") + g.Sc.ToString("X2") + "\r\n");
        return sb.ToString();
    }
    static void ResetKeys()
    {
        ChosenLayout = -1;
        foreach (GameKey g in GameKeys) g.Mouse = 0;
        for (int i = 0; i < ToolMouse.Length; i++) ToolMouse[i] = 0;
        foreach (GameKey g in GameKeys) { g.Sc = g.DefSc; g.Mod = g.DefMod; }
        ScanFreelook = 0x15; ScanNoclip = 0x16; ScanDistance = 0x24; ScanSmoothing = 0x40; ScanStereo = 0x41;
        ResolveToolClashes();
    }

    // a game command on a plain key the tool uses (the game's previous target on Y, freelook's key) goes to the
    // first free key of these: K L ; 7 8 9 0
    static readonly int[] SPARE_KEYS = { 0x25, 0x26, 0x27, 0x08, 0x09, 0x0A, 0x0B };
    static void ResolveToolClashes()
    {
        foreach (GameKey g in GameKeys)
            if (!g.Fixed && g.Mod == 0 && g.Sc < 0x80 && ToolKeyOwner(g.Sc, -1) >= 0)
                foreach (int f in SPARE_KEYS)
                    if (ToolKeyOwner(f, -1) < 0 && GameKeyOwner(f, 0, null) == null) { g.Sc = f; break; }
    }

    // ---- mouse binds: the middle button, the side buttons and the wheel can press a command's key (or do a tool
    // action) as a second bind; left and right buttons stay the game's (fire, lock). None by default.
    static readonly string[] MOUSE_NAMES = { "", "MID", "M4", "M5", "WH+", "WH-" };
    static readonly string[] MOUSE_INI = { "", "MID", "M4", "M5", "WHEELUP", "WHEELDOWN" };
    static readonly string[] MOUSE_LONG = { "", "middle click", "side button 4", "side button 5", "wheel up", "wheel down" };
    static readonly string[] TOOL_IDS = { "freelook", "noclip", "distance", "stereo", "smoothing" };   // KEY_WHAT order
    static readonly int[] ToolMouse = new int[5];

    static string MouseOwner(int m)
    {
        if (m == 0) return null;
        GameKey g = GameKeys.Find(k => k.Mouse == m);
        if (g != null) return g.Name.ToLowerInvariant();
        int t = Array.IndexOf(ToolMouse, m);
        return t >= 0 ? KEY_WHAT[t] : null;
    }

    // a mouse input to a game command (g) or a tool action (tool); m = 0 removes it
    static string AssignMouse(GameKey g, int tool, int m)
    {
        string name = g != null ? g.Name.ToLowerInvariant() : KEY_WHAT[tool];
        string before = MouseOwner(m);
        foreach (GameKey o in GameKeys) if (m != 0 && o.Mouse == m) o.Mouse = 0;
        for (int i = 0; i < ToolMouse.Length; i++) if (m != 0 && ToolMouse[i] == m) ToolMouse[i] = 0;
        if (g != null) g.Mouse = m; else ToolMouse[tool] = m;
        if (m == 0) return name + ": mouse bind removed";
        return name + ": " + MOUSE_LONG[m] + " (and still " + (g != null ? ChordName(g.Sc, g.Mod) : ScanName(GetKey(tool))) + ")" +
            (before != null && before != name ? ", taken from " + before : "");
    }

    static void ParseMouse(string id, string v)
    {
        int m = Array.IndexOf(MOUSE_INI, v.ToUpperInvariant());
        if (m <= 0) return;
        int t = Array.IndexOf(TOOL_IDS, id);
        GameKey g = FindGameKey(id);
        if (t >= 0) ToolMouse[t] = m; else if (g != null && !g.Fixed) g.Mouse = m;
    }
    static string MouseIni()
    {
        StringBuilder sb = new StringBuilder();
        foreach (GameKey g in GameKeys) if (g.Mouse > 0) sb.Append("mouse_" + g.Id + " = " + MOUSE_INI[g.Mouse] + "\r\n");
        for (int i = 0; i < ToolMouse.Length; i++) if (ToolMouse[i] > 0) sb.Append("mouse_" + TOOL_IDS[i] + " = " + MOUSE_INI[ToolMouse[i]] + "\r\n");
        return sb.ToString();
    }
    static bool AnyMouseBind() { return GameKeys.Exists(g => g.Mouse > 0) || Array.Exists(ToolMouse, m => m > 0); }

    // the command's key pressed as if typed (it goes through the key translation like the keyboard)
    [StructLayout(LayoutKind.Sequential)] struct KEYBDINPUT { public ushort wVk, wScan; public uint dwFlags, time; public IntPtr dwExtraInfo; }
    [StructLayout(LayoutKind.Sequential)] struct MOUSEINPUT { public int dx, dy; public uint mouseData, dwFlags, time; public IntPtr dwExtraInfo; }
    [StructLayout(LayoutKind.Explicit)] struct INPUTUNION { [FieldOffset(0)] public KEYBDINPUT ki; [FieldOffset(0)] public MOUSEINPUT mi; }
    [StructLayout(LayoutKind.Sequential)] struct INPUT { public uint type; public INPUTUNION u; }
    [DllImport("user32.dll", SetLastError = true)] static extern uint SendInput(uint n, INPUT[] inputs, int size);

    static void SendScan(int sc, bool up)
    {
        INPUT[] i = new INPUT[1];
        i[0].type = 1;
        i[0].u.ki.wScan = (ushort)(sc & 0x7F);
        i[0].u.ki.dwFlags = 0x0008 | (up ? 0x0002u : 0) | (sc >= 0x80 ? 0x0001u : 0);   // SCANCODE, KEYUP, EXTENDED
        SendInput(1, i, Marshal.SizeOf(typeof(INPUT)));
    }
    static void SendChord(GameKey g, bool down)
    {
        int msc = g.Mod == 1 ? 0x2A : g.Mod == 2 ? 0x1D : g.Mod == 3 ? 0x38 : 0;
        if (down) { if (msc != 0) SendScan(msc, false); SendScan(g.Sc, false); }
        else { SendScan(g.Sc, true); if (msc != 0) SendScan(msc, true); }
    }

    // ---- assigning keys: the same key is never used twice, the two swap when they can
    static readonly int[] MODIFIER_SC = { 0x1D, 0x2A, 0x36, 0x38 };
    static int ToolKeyOwner(int sc, int except)
    {
        for (int i = 0; i < KEY_WHAT.Length; i++) if (i != except && GetKey(i) == sc) return i;
        return -1;
    }
    static GameKey GameKeyOwner(int sc, int mod, GameKey except)
    {
        return GameKeys.Find(g => g != except && g.Sc == sc && g.Mod == mod);
    }

    // a game command gets a new key; returns the message to show
    static string AssignGameKey(GameKey g, int sc, int mod, bool ext)
    {
        if (ext || sc <= 1 || sc >= 0x80 || Array.IndexOf(MODIFIER_SC, sc) >= 0)
            return "that key can't be used (Esc, extended keys like the arrows): pick another one";
        if (sc == g.Sc && mod == g.Mod) return g.Name.ToLowerInvariant() + ": unchanged";
        GameKey o = GameKeyOwner(sc, mod, g);
        int t = mod == 0 ? ToolKeyOwner(sc, -1) : -1;
        if (o != null && o.Fixed) return ChordName(sc, mod) + " is the game's " + o.Name.ToLowerInvariant() + " key: pick another one";
        if (t >= 0 && (g.Mod != 0 || g.Sc >= 0x80 || Array.IndexOf(KEY_RESERVED, g.Sc) >= 0))
            return ChordName(sc, mod) + " is Terra Nova Plus " + KEY_WHAT[t] + ": change that one first";
        string msg = g.Name.ToLowerInvariant() + ": " + ChordName(sc, mod);
        if (o != null) { o.Sc = g.Sc; o.Mod = g.Mod; msg += ", " + o.Name.ToLowerInvariant() + " moved to " + ChordName(o.Sc, o.Mod); }
        if (t >= 0) { SetKey(t, g.Sc); msg += ", " + KEY_WHAT[t] + " moved to " + ScanName(g.Sc); }
        g.Sc = sc; g.Mod = mod;
        return msg;
    }

    // a key of the tool itself (plain key); returns the message, null when refused with the reserved-key text
    static string AssignToolKey(int k, int sc, bool ext)
    {
        if (ext || sc == 0 || Array.IndexOf(KEY_RESERVED, sc) >= 0)
            return "that key is taken by the game or the tool (Esc, O, noclip up / down, Ctrl, Shift, Alt, arrows...): pick another one";
        if (sc == GetKey(k)) return KEY_WHAT[k] + ": unchanged";
        string msg = KEY_WHAT[k] + ": " + ScanName(sc);
        int other = ToolKeyOwner(sc, k);
        GameKey o = GameKeyOwner(sc, 0, null);
        if (o != null && o.Fixed) return ScanName(sc) + " is the game's " + o.Name.ToLowerInvariant() + " key: pick another one";
        if (other >= 0) { SetKey(other, GetKey(k)); msg += ", " + KEY_WHAT[other] + " moved to " + ScanName(GetKey(other)); }
        if (o != null) { o.Sc = GetKey(k); o.Mod = 0; msg += ", " + o.Name.ToLowerInvariant() + " moved to " + ScanName(o.Sc); }
        SetKey(k, sc);
        return msg;
    }

    // ---- keyboard layout presets. GAME = the game's own keys. The others: moves on W A S D as in today's games
    // (Z Q S D on AZERTY: the game reads key positions): S back and X stop (the game: S stop, X back), A / D sidestep
    // and Z / C turn (the game: A / D turn, Z / C sidestep);
    // look and number keys keep their place; the letter shortcuts follow the letter printed on the keyboard, a letter
    // that lands on a key already used keeps the game's place. Other QWERTY countries (UK, ES, IT, Nordic...) have
    // their letters where QWERTY has them.
    static readonly string[] LAYOUT_NAMES = { "GAME", "QWERTY", "AZERTY", "QWERTZ", "DVORAK", "COLEMAK", "CUSTOM" };
    const int LAYOUT_COUNT = 6;
    static readonly string[][] LAYOUT_ROWS = {      // letter rows from scancodes 0x10, 0x1E, 0x2C
        new[] { "QWERTYUIOP", "ASDFGHJKL;", "ZXCVBNM" },
        new[] { "AZERTYUIOP", "QSDFGHJKLM", "WXCVBN" },
        new[] { "QWERTZUIOP", "ASDFGHJKL", "YXCVBNM" },
        new[] { "',.PYFGCRL", "AOEUIDHTNS", ";QJKXBMWVZ" },
        new[] { "QWFPGJLUY;", "ARSTDHNEIO", "ZXCVBKM" } };
    static readonly string[,] LETTER_KEYS = {
        { "full", "G" }, { "ir", "I" }, { "recentre", "N" }, { "v360", "B" }, { "maphud", "M" }, { "pause", "P" },
        { "tnext", "T" }, { "tprev", "Y" }, { "o_attack", "A" }, { "o_cover", "C" }, { "o_caution", "D" }, { "o_form", "F" },
        { "o_hold", "H" }, { "o_follow", "M" }, { "o_nav", "N" }, { "o_pickup", "P" }, { "o_retreat", "R" },
        { "o_status", "S" }, { "o_target", "T" }, { "exit", "X" } };

    // the other keys a command can use, as printed on each keyboard (the digits are the same everywhere)
    static readonly string[][] LAYOUT_PUNCT = {      // scancodes 0C 0D 1A 1B 28 29 2B 32 33 34 35 (empty: a letter row)
        new[] { "-", "=", "[", "]", "'", "`", "\\", "", ",", ".", "/" },
        new[] { ")", "=", "^", "$", "\u00d9", "\u00b2", "*", ",", ";", ":", "!" },
        new[] { "\u00df", "\u00b4", "\u00dc", "+", "\u00c4", "^", "#", "", ",", ".", "-" },
        new[] { "[", "]", "/", "=", "-", "`", "\\", "", "", "", "" },
        new[] { "-", "=", "[", "]", "'", "`", "\\", "", ",", ".", "/" } };
    static readonly int[] PUNCT_SC = { 0x0C, 0x0D, 0x1A, 0x1B, 0x28, 0x29, 0x2B, 0x32, 0x33, 0x34, 0x35 };

    // keys are shown as printed on the keyboard of the preset picked (GAME, CUSTOM: the Windows keyboard)
    static int DisplayLayout() { return ChosenLayout >= 1 && ChosenLayout < LAYOUT_COUNT ? ChosenLayout : -1; }
    static string LayoutKeyName(int layout, int sc)
    {
        if (sc >= 0x02 && sc <= 0x0B) return sc == 0x0B ? "0" : ((char)('1' + sc - 2)).ToString();
        int[] start = { 0x10, 0x1E, 0x2C };
        for (int r = 0; r < 3; r++)
        {
            string row = LAYOUT_ROWS[layout - 1][r];
            if (sc >= start[r] && sc < start[r] + row.Length) return row[sc - start[r]].ToString();
        }
        int i = Array.IndexOf(PUNCT_SC, sc);
        return i >= 0 && LAYOUT_PUNCT[layout - 1][i] != "" ? LAYOUT_PUNCT[layout - 1][i] : null;
    }

    static int LetterSc(int layout, char c)
    {
        int[] start = { 0x10, 0x1E, 0x2C };
        for (int r = 0; r < 3; r++) { int i = LAYOUT_ROWS[layout - 1][r].IndexOf(c); if (i >= 0) return start[r] + i; }
        return 0;
    }

    // the chords a preset gives: game defaults, then the letters, as long as they land on a free key
    static int[,] LayoutChords(int layout)
    {
        int n = GameKeys.Count;
        int[,] ch = new int[n, 2];
        for (int i = 0; i < n; i++) { ch[i, 0] = GameKeys[i].DefSc; ch[i, 1] = GameKeys[i].DefMod; }
        if (layout > 0) LayoutMoves(layout, ch);
        for (int i = 0; i < n; i++)                 // off the tool's keys, like ResolveToolClashes
            if (ch[i, 1] == 0 && ToolKeyOwner(ch[i, 0], -1) >= 0)
                foreach (int f in SPARE_KEYS)
                {
                    bool used = ToolKeyOwner(f, -1) >= 0;
                    for (int j = 0; j < n && !used; j++) used = ch[j, 0] == f && ch[j, 1] == 0;
                    if (!used) { ch[i, 0] = f; break; }
                }
        return ch;
    }

    static void LayoutMoves(int layout, int[,] ch)
    {
        int n = GameKeys.Count;
        Func<string, int> at = id => GameKeys.FindIndex(g => g.Id == id);
        ch[at("back"), 0] = 0x1F; ch[at("stop"), 0] = 0x2D;        // S back, X stop
        ch[at("sidel"), 0] = 0x1E; ch[at("sider"), 0] = 0x20;      // A / D sidestep (strafe), the mouse turns
        ch[at("turnl"), 0] = 0x2C; ch[at("turnr"), 0] = 0x2E;      // Z / C turn
        for (bool moved = true; moved; )
        {
            moved = false;
            for (int k = 0; k < LETTER_KEYS.GetLength(0); k++)
            {
                int i = GameKeys.FindIndex(g => g.Id == LETTER_KEYS[k, 0]);
                int sc = LetterSc(layout, LETTER_KEYS[k, 1][0]);
                if (i < 0 || sc == 0 || sc == ch[i, 0]) continue;
                bool free = !(ch[i, 1] == 0 && ToolKeyOwner(sc, -1) >= 0);
                for (int j = 0; j < n && free; j++) if (j != i && ch[j, 0] == sc && ch[j, 1] == ch[i, 1]) free = false;
                if (free) { ch[i, 0] = sc; moved = true; }
            }
        }
    }

    static int ChosenLayout = -1;                   // ini keys_layout: the preset picked last (QWERTZ gives QWERTY's keys)

    static void ApplyLayout(int layout)
    {
        ChosenLayout = layout;
        int[,] ch = LayoutChords(layout);
        for (int i = 0; i < GameKeys.Count; i++) { GameKeys[i].Sc = ch[i, 0]; GameKeys[i].Mod = ch[i, 1]; }
    }

    // the preset the game keys match (the detected layout first), or CUSTOM
    static int CurrentLayout()
    {
        int det = DetectLayout();
        List<int> order = new List<int>();
        if (ChosenLayout >= 0 && ChosenLayout < LAYOUT_COUNT) order.Add(ChosenLayout);
        if (!order.Contains(det)) order.Add(det);
        for (int l = 0; l < LAYOUT_COUNT; l++) if (!order.Contains(l)) order.Add(l);
        foreach (int l in order)
        {
            int[,] ch = LayoutChords(l);
            bool same = true;
            for (int i = 0; i < GameKeys.Count && same; i++) same = GameKeys[i].Sc == ch[i, 0] && GameKeys[i].Mod == ch[i, 1];
            if (same) return l;
        }
        return LAYOUT_COUNT;
    }

    // the Windows keyboard layout, from where its letters are
    static int DetectLayout()
    {
        Func<char, uint> sc = c => MapVirtualKey((uint)c, 0);
        if (sc('A') == 0x10) return 2;
        if (sc('Z') == 0x15) return 3;
        if (sc('P') == 0x13) return 4;
        if (sc('F') == 0x12) return 5;
        return 1;
    }

    // ---- in the game (addresses: _MODS/re/kb_cave.json)
    const uint KB_CODE = 0x46AA20, KB_INSTALL = 0x46AA20, KB_MAP_FN = 0x46AA92, KB_DATA = 0x469A10, KB_DATA_END = 0x469F30;
    const uint KB_ACTIVE = 0x469A10, KB_STATE = 0x469A14, KB_SITE = 0x469A18, KB_RESUME = 0x469A1C, KB_PM = 0x469A20;
    const uint KB_PATCH = 0x469A24, KB_ACT = 0x469A30, KB_MAP = 0x469B30;
    static readonly uint[] KB_HOOK = { 0x29E828, 0x29E838 };   // camera set-up: mov [esp+4], edx / mov [esp+8], ebx
    const string KB_HOOK_OLD = "89542404895C2408", KB_SITE_SIG = "0FBEC0257F01000080F4010AE47423", KB_RESUME_SIG = "C1E2088AD0895304";
    const string KB_CODE_HEX =
        "833D149A46000175259CFA565751BE249A46008B3D189A4600B90B000000F3A4595F5E9DC705149A46000200000089542408895C240CC3510FB6C8F6C401740A808C0B1004000001EB0880A40B10040000FE8B0B81E1FFFF00006689041983C10281F910" +
        "0400007205B910000000890B59C35755520FB6C05089C183E07F31ED83F82A7505BD0100000083F8367505BD0200000083F81D7505BD0400000083F8387505BD0800000085ED741DF6C180750B092D209A4600E94B030000F7D5212D209A4600E93E0300" +
        "00F6C1800F85440200000FB73445309A4600F7C6008000000F8509020000F7C6004000000F8515030000833D109A4600000F84E10100008B15209A460031FFF7C203000000740383CF01F7C204000000740383CF02F7C208000000740383CF0483FF0074" +
        "1883FF01741383FF02740E83FF040F85A0010000BF030000008D34870FB73475309B4600F7C600800000754683FF030F847F01000085FF0F84770100000FB734C5309B4600F7C6008000000F8463010000F7C600030000751989F781E7FF00000081FFFF" +
        "0000000F8438010000E91001000089F781E7FF00000081FFFF0000000F841F010000C1EE0883E60331ED8B15209A460083FE017436F7C203000000744881CD0008000050F7C201000000740AB82A000000E851FEFFFFF7C202000000740AB836000000E8" +
        "3FFEFFFF58EB1AF7C203000000751281CD0001000050B82A010000E823FEFFFF5883FE02741CF7C204000000742E81CD0010000050B81D000000E804FEFFFF58EB1AF7C204000000751281CD0002000050B81D010000E8E8FDFFFF5883FE03741CF7C208" +
        "000000742E81CD0020000050B838000000E8C9FDFFFF58EB1AF7C208000000751281CD0004000050B838010000E8ADFDFFFF5809FD81CD0080000066892C45309A46005089F80D00010000E88FFDFFFF58E97301000089FD81CD0080000066892C45309A" +
        "46005089F80D00010000E86CFDFFFF58E95001000066C70445309A4600FF80E94101000066C70445309A46000040E91801000089F781E7FF00000081FFFF0000000F841E0100005089F80D00010000E827FDFFFF58E90B0100000FB73445309A460066C7" +
        "0445309A46000000F7C6008000000F84D300000089F781E7FF00000081FFFF0000000F84D90000005089F8E8E7FCFFFF8B15209A4600F7C6000100007412F7C203000000750AB82A000000E8C7FCFFFFF7C6000200007412F7C204000000750AB81D0000" +
        "00E8ADFCFFFFF7C6000400007412F7C208000000750AB838000000E893FCFFFFF7C6000800007424F7C201000000740AB82A010000E879FCFFFFF7C202000000740AB836010000E867FCFFFFF7C6001000007412F7C204000000740AB81D010000E84DFC" +
        "FFFFF7C6002000007412F7C208000000740AB838010000E833FCFFFF58EB1A5989C883E07F81F180000000D1E181E10001000009C85A5D5FC3585A5D5F8B0D1C9A4600890C24C3";
    static int keysState = 0;                       // 0 to do, 1 in place, -1 nothing to change or unavailable
    static bool keysActive = false;

    static byte[] Rel32Call(uint from, uint to, int len)
    {
        byte[] b = new byte[len];
        b[0] = 0xE8; BitConverter.GetBytes((int)(to - (from + 5))).CopyTo(b, 1);
        for (int i = 5; i < len; i++) b[i] = 0x90;
        return b;
    }

    // 128 keys x (none, Shift, Ctrl, Alt): 0 nothing; 0x8000 | game key | its modifier << 8; 0x80FF = key taken away
    static byte[] BuildKeyMap()
    {
        ushort[] map = new ushort[512];
        foreach (GameKey g in GameKeys)
            if (g.Changed && !g.Fixed && g.Sc < 0x80) map[g.Sc * 4 + g.Mod] = (ushort)(0x8000 | g.DefSc | (g.DefMod << 8));
        foreach (GameKey g in GameKeys)
            if (g.Changed && g.DefSc < 0x80 && GameKeyOwner(g.DefSc, g.DefMod, null) == null) map[g.DefSc * 4 + g.DefMod] = 0x80FF;
        byte[] b = new byte[1024];
        Buffer.BlockCopy(map, 0, b, 0, 1024);
        return b;
    }

    static bool AllZero(byte[] b) { foreach (byte x in b) if (x != 0) return false; return true; }

    static void TryKeys()
    {
        keysState = -1;
        int n = GameKeys.FindAll(g => g.Changed).Count;
        if (n == 0)
        {   // nothing changed now, but an earlier run may have left its table in this game: emptied
            uint st = ReadUInt(KB_STATE);
            if (st == 1 || st == 2) { WriteInt(KB_ACTIVE, 0); Write(KB_MAP, new byte[1024]); }
            return;
        }
        uint site = 0, s0 = ReadUInt(KB_SITE);
        if (s0 > 0x200000 && s0 < 0x340000 && Same(Read(s0, 11), Rel32Call(s0, KB_MAP_FN, 11))) site = s0;   // already in place
        else
        {
            byte[] mem = Read(0x300000, 0x40000);
            int i = mem == null ? -1 : IndexOf(mem, Hex(KB_SITE_SIG), 0);
            if (i >= 0) site = 0x300000 + (uint)i;
        }
        if (site == 0 || !Same(Read(site + 0x6A, 8), Hex(KB_RESUME_SIG))) { Say("Game keys unavailable: keyboard handler not found", 300, 300); return; }
        int lang = -1;
        for (int l = 0; l < 2; l++)
        {
            byte[] h = Read(KB_HOOK[l], 8);
            if (Same(h, Hex(KB_HOOK_OLD)) || Same(h, Rel32Call(KB_HOOK[l], KB_INSTALL, 8))) lang = l;
        }
        byte[] code = Hex(KB_CODE_HEX), cur = Read(KB_CODE, code.Length);
        bool placed = s0 == site && ReadUInt(KB_STATE) >= 1;
        if (lang < 0 || (!AllZero(cur) && !Same(cur, code)) || (!placed && !AllZero(Read(KB_DATA, (int)(KB_DATA_END - KB_DATA)))))
        {
            Say("Game keys unavailable: unexpected game code or memory", 300, 300); return;
        }
        WriteInt(KB_ACTIVE, 0); keysActive = false;
        Write(KB_MAP, BuildKeyMap());
        if (!placed)
        {
            Write(KB_ACT, new byte[256]); WriteInt(KB_PM, 0);
            WriteInt(KB_SITE, (int)site); WriteInt(KB_RESUME, (int)(site + 0x6A));
            Write(KB_PATCH, Rel32Call(site, KB_MAP_FN, 11));
            Write(KB_CODE, code);                    // the code first, then what calls it
            WriteInt(KB_STATE, 1);
            Write(KB_HOOK[lang], Rel32Call(KB_HOOK[lang], KB_INSTALL, 8));
        }
        keysState = 1;
        Say("Game keys: " + n + " changed, active in missions", 0);
    }

    // during missions only: the menus and the names typed keep the keyboard as it is
    static void KeysFollowMission(bool inMission)
    {
        if (keysState != 1 || inMission == keysActive) return;
        keysActive = inMission;
        WriteInt(KB_ACTIVE, inMission ? 1 : 0);
    }
}
